# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'JFrog Platform V2'
    command: | 
      jf rt ping
      jf npmc --repo-resolve alpha-npm-virtual --repo-deploy alpha-npm-virtual

- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'JFrog Artifactory V2'
    sourceRepo: 'alpha-npm-virtual'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'JFrog Artifactory V2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JfrogCliV2@1
  name: 'BuildScan'
  inputs:
    jfrogPlatformConnection: 'JFrog Platform V2'
    command: | 
      jf bs '$(Build.DefinitionName)' '$(Build.BuildNumber)'
      
